// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtwWd_CDQFvEWl44hbdmemcm405E61Kxg',
    appId: '1:905671345185:web:9a74c844ce0499ca194f60',
    messagingSenderId: '905671345185',
    projectId: 'employee-db-473f2',
    authDomain: 'employee-db-473f2.firebaseapp.com',
    databaseURL: 'https://employee-db-473f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-473f2.firebasestorage.app',
    measurementId: 'G-8NCNH4DL4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCVOrxWfV4qmQIsvfgAiaZ_aL3s3QUP8U',
    appId: '1:905671345185:android:738c144d16a90585194f60',
    messagingSenderId: '905671345185',
    projectId: 'employee-db-473f2',
    databaseURL: 'https://employee-db-473f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-473f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQR4MFdICNTVQHEwxB72L0-dv7L_r-XXk',
    appId: '1:905671345185:ios:45d6a93f886a2d82194f60',
    messagingSenderId: '905671345185',
    projectId: 'employee-db-473f2',
    databaseURL: 'https://employee-db-473f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-473f2.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQR4MFdICNTVQHEwxB72L0-dv7L_r-XXk',
    appId: '1:905671345185:ios:45d6a93f886a2d82194f60',
    messagingSenderId: '905671345185',
    projectId: 'employee-db-473f2',
    databaseURL: 'https://employee-db-473f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-473f2.firebasestorage.app',
    iosBundleId: 'com.example.employee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtwWd_CDQFvEWl44hbdmemcm405E61Kxg',
    appId: '1:905671345185:web:8cbf42e10c9783ba194f60',
    messagingSenderId: '905671345185',
    projectId: 'employee-db-473f2',
    authDomain: 'employee-db-473f2.firebaseapp.com',
    databaseURL: 'https://employee-db-473f2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'employee-db-473f2.firebasestorage.app',
    measurementId: 'G-BJERP78780',
  );
}
